# Generated by Django 6.0.6 on 2026-07-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComebackReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(help_text='Día (0, 1, 2...) en el que se desbloquea.', unique=True)),
                ('text', models.TextField()),
            ],
        ),
    ]
