# Generated by Django 6.0.6 on 2026-07-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_nostalgicsong_unsentletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistsong',
            name='is_sad',
            field=models.BooleanField(default=False),
        ),
    ]
